### ISSUE TITLE
Missing .cmake files?

### ISSUE THREAD

**Issue by Kiguli** [mkhaled87/pFaces-AMYTISS#1]
Hello, 

I am trying to install AMYTISS on my Macbook 2020 (Intel version i5 CPU chip). 

I get the following error:
`CMake Error at CMakeLists.txt:10 (include):
  include could not find requested file:

    /PATH/.../pFaces-1.2.1-MacOS12.0.1/pfaces-sdk/pfaces_kernel.cmake

CMake Error at CMakeLists.txt:35 (include):
  include could not find requested file:

    /PATH/.../pFaces-1.2.1-MacOS12.0.1/pfaces-sdk/pfaces_link.cmake` 

I have been following the installation instructions closely but I don't seem to have these files. Is there a better way to do the installation?

I thought this route might be a bit faster than learning how to pass my CPU to docker.

I appreciate any help you can provide :)

**Comment by mkhaled87** [comment]
Hi, I guess you are receiving this because you are using the main branch which is currently under dev (I am upgrading to newwer version of pFaces that already has these files). 
Please use this tag/branch:
`https://github.com/mkhaled87/pFaces-AMYTISS/tree/PFACES_UP_TO_1.2
`
This should work with the available latest pFaces version.

Give it another try a d let me know if this solves the issue.

**Comment by Kiguli** [comment]
Thanks, I was able to install AMYTISS. However, I now get an error when I run the example toy2d.cfg. Here is the build log:

-----------------------------------------------------------------
Build log started on Friday 25/08/2023 14:16:36-896
-----------------------------------------------------------------
Number of devices: 1
Devices: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz; 
Purpose: Building context for a run on a single devices.
OpenCL compiler params: -cl-std=CL1.2 -cl-kernel-arg-info -I/Users/kiguli/Documents/My_papers/IMDPTool/AMYTISS/pFaces-1.2.1-MacOS12.0.1/bin/kernels/ -I../../kernel-pack/ -DUNIVERSAL_WIDTH_X=1681 -DUNIVERSAL_WIDTH_Y=441 -DUNIVERSAL_OFFSET_X=0 -DUNIVERSAL_OFFSET_Y=0 -DPROCESS_WIDTH_X=1681 -DPROCESS_WIDTH_Y=441 -DPROCESS_OFFSET_X=0 -DPROCESS_OFFSET_Y=0
Kernel file: ../../kernel-pack/amytiss.cpu.cl.render
-----------------------------------------------------------------
Failed to build the kernel(../../kernel-pack/amytiss.cpu.cl.render) and the following is the build log: 

Build log for  Dev. [Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz] with options (-cl-std=CL1.2 -cl-kernel-arg-info -I /PATH/AMYTISS/pFaces-1.2.1-MacOS12.0.1/bin/kernels/ -I "/PATH/AMYTISS/pFaces-AMYTISS-PFACES_UP_TO_1.2/examples/ex_toy_reachavoid"/../../kernel-pack/ -DUNIVERSAL_WIDTH_X=1681 -DUNIVERSAL_WIDTH_Y=441 -DUNIVERSAL_OFFSET_X=0 -DUNIVERSAL_OFFSET_Y=0 -DPROCESS_WIDTH_X=1681 -DPROCESS_WIDTH_Y=441 -DPROCESS_OFFSET_X=0 -DPROCESS_OFFSET_Y=0):
<program source>:13:10: fatal error: 'pfaces.cl' file not found
#include "pfaces.cl"
         ^

-----------------------------------------------------------------
Build ended
-----------------------------------------------------------------

**Comment by mkhaled87** [comment]
This is a known issue that happens with intel ocl driver when using intel CPUs on some machines/OSs. This will be  fixed in the next version of pFaces, which I am currently trying to finalize. For now, using Docker is a solution: to use all cpu cores in the container, in the settings of docket set the number of cpu cores to the max you can set to.

**Comment by Kiguli** [comment]
Thanks, I'll do that. Cheers :)
